#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:mysql://mysql:3306/jun-mysql?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: jun
#    password: 0000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true